### ISSUE TITLE
Add battery meter

### ISSUE THREAD

**Issue by dbrgn** [coredump-ch/watertemp#10]
We should be able to track the battery voltage and/or charge in percent.

**Comment by rnestler** [comment]
Didn't we plan to have like a battery management system which manages all this and provides the charge?

**Comment by dbrgn** [comment]
The board by Adafruit unfortunately only reports a binary battery low warning, but no voltage level.

**Comment by dbrgn** [comment]
Closed in favor of https://github.com/coredump-ch/watertemp-hardware/issues/4
