### ISSUE TITLE
Choose a micro-controller

### ISSUE THREAD

**Issue by rnestler** [coredump-ch/watertemp#3]
We need to find a suiting micro-controller.

The following features would be nice:
- ARM based
- [openocd](http://openocd.org/) support
- mbed compatible
- cheap
- low-power

Options:
- [LPC11U12FBD48/201](http://www.digikey.com/product-detail/en/nxp-semiconductors/LPC11U12FBD48-201,/568-8582-ND/2791874)
- [LPC11U24FHI33/301](http://www.digikey.com/product-detail/en/nxp-semiconductors/LPC11U24FHI33-301,/568-8523-ND/2772164)

**Comment by dbrgn** [comment]
We'll use this one:
- IC MCU 32BIT 32KB FLASH 48LQFP
- Model: LPC11U24FBD48/401
- Package: 48-LQFP
- Digikey: 568-8460-ND
- Price: USD 3.71

https://www.digikey.com/product-detail/en/nxp-semiconductors/LPC11U24FBD48-401,/568-8460-ND/2771727

**Comment by rnestler** [comment]
Debugging: https://sourceforge.net/projects/lpc21isp/
